# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49c76536561d9bf3d80722e943b5f1f0ddb7a42efcdcd2c4271bcd12691034411645373d74089fb1423ac568358f688eb00b6a741ed2a2cdd44add5b217f6d7e

test:
  secret_key_base: 0af3e464a23d0302247c0dcb65f82b040ffe665bd834a10bb3a13e67039c226936cd58c1be3558a64306f7c87d5199ccbe3d5b3fde69528842f385ebe6e81c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
